# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4a8e1a9af1d2603a7f85117b927b130fe6707d887d197d41e46c917ad10bfcb1b8959cedb363439c268f73ec945071b855bd285d581b15baa4c83018a3eb72a

test:
  secret_key_base: fdf6b64d14c3dfff9e2f6e5bb1e38102e969b152ee924dd6017d296867a9e2d55a92f5d4429ffc075bcac17667ad8d76eca0a29b2b4031c39b1bbace095f69d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
